### ISSUE TITLE
Add support for SSL keystores

### ISSUE THREAD

**Issue by ggreen** [spring-cloud-stream-app-starters/gemfire#12]
Looks like the out of the box gemfire sink does not support using SSL keystores. 
I would suggest loading the keystore dynamically instead of relying on it being loaded from a directory.

It can support loading the keystore from an environment variable (encoded as a string) or from the classpath similar to following online example.

[Example Loading Keystore for classpath]
https://stackoverflow.com/questions/35847703/how-to-embed-a-keystore-certificate-only-during-runtime-from-classpath

I prefer the environment variable option since it would not require rebuilding the Spring Boot jars when the certificates expire. This also makes it easier to configure different certs all using the same spring boot jar.

**Comment by sabbyanandan** [comment]
Here's prior work on adding this support to the OOTB apps -> https://github.com/pvermeulen-pivotal/GemFire-SCDF-Enhancement -- we would want to review to see how it can be adapted in the formal Apps and as well the delivery mechanism for the cert customizations.
