### ISSUE TITLE
Add support for GemFire 9.5.1

### ISSUE THREAD

**Issue by MHarris021** [spring-cloud-stream-app-starters/gemfire#15]
I would greatly appreciate it if SCDF could support connecting to GemFire 9.5.1. My understanding from talking to the PM for the Spring Data GemFire project is that it would require SCDF to bump up the version of the Spring Data Release train BOM.

**Comment by sabbyanandan** [comment]
We are currently compatible with Pivotal Gemfire v.9.1.1 and Apache Geode v1.2.1.

The v2.1.0 of `spring-data-gemfire`appears to support [v9.5.1](https://github.com/spring-projects/spring-data-gemfire/blob/master/pom.xml#L25); however, we rely on Geode OSS backed by `spring-data-geode`. Most likely [v.2.1.0](https://github.com/spring-projects/spring-data-geode/blob/master/pom.xml#L25) of this project should support it, but we will have to confirm with the Spring Data team. Also, we won't be able to upgrade until the dependent projects are released as v2.1.0 GA milestone.

cc:/ @jxblum

**Comment by jxblum** [comment]
Please keep in mind there are 2 SD projects related to Apache Geode and Pivotal GemFire.  There is _**Spring Data for Apache Geode**_ and then there is _**Spring Data for Pivotal GemFire**_.  As of SD **Kay**, these dependencies are interchangeable.  Meaning, if a user is coming from the OSS space, using _Spring Data for Apache Geode_, then she can simply switch to Pivotal GemFire by changing the dependency from `spring-data-geode` to `spring-data-gemfire`, providing they are using SD **Kay** or the soon to be GA release of SD **Lovelace**.  The version number between these modules are the same.

See [my last year's S1P presentation](https://www.youtube.com/watch?v=OvY5wzCtOV0) for more details.  The slides are [here](https://www.slideshare.net/Pivotal/simplifying-apache-geode-with-spring-data).  Please observe slides 7 & 8.

As of SD **Lovelace**, SD for Apache Geode (2.1) is based on Apache Geode 1.6.0.  SD for Pivotal GemFire (2.1) is based on Pivotal GemFire 9.5.1, which is itself based on Apache Geode 1.6.0.

My intention is to ensure `spring-data-geode` and `spring-data-gemfire` are interchangeable, always, within a given SD release train, either forward or back.

Hope this makes sense!

Also have a look at my [blog post](https://spring.io/blog/2017/10/26/diff-q-spring-data-gemfire-spring-data-geode).

Cheers!

**Comment by jxblum** [comment]
For further clarification, this also means that, if SCDF is based on SD **Kay**, using the OS _Spring Data for Apache Geode_ to build support for Apache Geode/Pivotal GemFire (indirectly), and a user wants to use _Spring Data for Pivotal GemFire_ with Pivotal GemFire and SCDF instead, then you can simply exclude the `spring-data-geode` dependency and explicitly include the `spring-data-gemfire` dependency.

This is exactly how the _Spring Boot_, _Spring Session_ and _Spring Test_ support works now.   See [here](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-gemfire-starter/spring-gemfire-starter.gradle#L14-L22) for _Spring Boot for Pivotal GemFire_ (`org.springframework:geodespring-gemfire-starter`) or the [here](https://github.com/spring-projects/spring-session-data-geode/blob/master/spring-session-data-gemfire/spring-session-data-gemfire.gradle#L7-L11) for _Spring Session for Pivotal GemFire_.

Therefore, if you are importing a version of SCDF that includes SDG, then swapping the Geode dependency for the GemFire one would be nearly the same, except the exclude `spring-data-geode` would be on the SCDF dependency.

**Comment by sabbyanandan** [comment]
Thanks, @jxblum! I find your blog post on the differences between Gf/Geode as very useful. I get the interchangeable aspect - neat. 

As next steps, we would have to upgrade SD stack to Lovelace to pull the latest releases to support GF 9.5.1 - we will plan for that. Do you know the GA timeline for Lovelace? 

Also,

> As of SD Lovelace, SD for Apache Geode (2.1) is based on Apache Geode 1.6.0. SD for Pivotal GemFire (2.1) is based on Pivotal GemFire 9.5.1, which is itself based on Apache Geode 1.6.0.

It'd still be useful to have a table or a running wiki that list the compatibility matrix. I can't easily find out how the lowest dependency (geode) bubbles all the way to s-d-geode and s-c-gemfire. 

We have had similar issues with Kafka - see [here](https://github.com/spring-cloud/spring-cloud-stream/wiki/Kafka-Client-Compatibility).

**Comment by jxblum** [comment]
Well, the easiest thing is to keep in mind that my guarantee will be that SD for Apache Geode & SD for Pivotal GemFire will be interchangeable for a given SD _Release Train_ (e.g. **Kay**, **Lovelace**, and eventually **Moore** (which is `Lovelace.next`).  I.e., if you are using SD for Apache Geode **Kay** and want to use Spring anything with Pivotal GemFire instead, then use SD for Pivotal GemFire **Kay**.  The same applies to SD **Lovelace**.

SD Lovelace final GA is scheduled tentatively for **Wednesday, September 19th**, according to the [Spring Release Calendar](https://spring-calendar.cfapps.io/).

Finally, I have also maintained this [version compatibility Wiki page](https://github.com/spring-projects/spring-data-gemfire/wiki/Spring-Data-GemFire-to-GemFire-Version-Compatibility) between _Spring Data_ and Pivotal GemFire for sometime.

I might be will to do something similar for _Spring Data for Apache Geode_ and/or add an additional Wiki page that shows the complete SD, Apache Geode and Pivotal GemFire version matrix.
