### ISSUE TITLE
Gemfire-source to log failing

### ISSUE THREAD

**Issue by sgulzar-pivotal** [spring-cloud-stream-app-starters/gemfire#2]
Unable to deploy a stream on scdf (version spring-cloud-dataflow-server-local-1.1.2.RELEASE.jar) and pcfdev (spring-cloud-dataflow-server-cloudfoundry-1.1.0.M1.jar)  to pull the data from Gemfire and write it to logs.

**stream definition:**
stream create --name test --definition "gemfire --region-name=Transaction --host-addresses=192.168.11.1:10334 | log" --deploy

Used Stream App Starters and Spring Cloud Data Flow -
http://bit.ly/Avogadro-SR1-stream-applications-rabbit-maven  and 
http://bit.ly/Avogadro-SR1-stream-applications-kafka-10-maven  ( I have a local kakfa .10 running)

Gemfire Version:
Tried the following version: geode 1.0.0-incubating, gemfire 8.2, gemfire 9.

dataflow:>app import --uri http://bit.ly/Avogadro-SR1-stream-applications-rabbit-maven
Successfully registered applications: [sink.task-launcher-yarn, source.tcp, sink.jdbc, source.http, sink.rabbit, source.rabbit, source.ftp, sink.gpfdist, processor.transform, source.loggregator, source.sftp, processor.filter, source.file, sink.cassandra, processor.groovy-filter, sink.router, source.trigger, sink.hdfs-dataset, processor.splitter, source.load-generator, sink.sftp, sink.file, processor.tcp-client, sink.tasklaunchrequest-transform, source.time, source.gemfire, source.twitterstream, sink.tcp, source.jdbc, sink.field-value-counter, sink.redis-pubsub, sink.hdfs, sink.task-launcher-local, processor.bridge, processor.pmml, processor.httpclient, sink.ftp, source.s3, sink.log, sink.gemfire, sink.aggregate-counter, sink.throughput, source.triggertask, sink.s3, source.gemfire-cq, source.jms, source.tcp-client, processor.scriptable-transform, sink.counter, sink.websocket, source.mongodb, source.mail, processor.groovy-transform, source.syslog]

Error from logs:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gemfirePool' defined in org.springframework.cloud.stream.app.gemfire.config.GemfirePoolConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.gemfire.client.PoolFactoryBean]: Factory method 'gemfirePool' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.data.gemfire.client.PoolFactoryBean.setLocatorEndpointList(Lorg/springframework/data/gemfire/support/ConnectionEndpointList;)V

**Comment by artembilan** [comment]
This has been fixed via https://github.com/spring-cloud-stream-app-starters/gemfire/commit/9059901f464034da9010f5302b6d6f920466f45c.

Or try to use `<version>1.1.2.BUILD-SNAPSHOT</version>` for the `gem fire source` or until we release that fix for this gen fire application set.

**Comment by sgulzar-pivotal** [comment]
Compiled the gemfire-source and registered the app using 
app register --name gemfire --type source --uri file:///Users/gulzas/Demo_CAB/gemfire-master/spring-cloud-starter-stream-source-gemfire/target/spring-cloud-starter-stream-source-gemfire-1.1.2.BUILD-SNAPSHOT.jar

Now getting a different error while deploying the stream-- no main manifest attribute, in /Users/gulzas/Demo_CAB/gemfire-master/spring-cloud-starter-stream-source-gemfire/target/spring-cloud-starter-stream-source-gemfire-1.1.2.BUILD-SNAPSHOT.jar

Not sure if I am using correct procedure.

**Comment by artembilan** [comment]
Do you use `-PgenerateApps` profile? 

Then in the `/apps` You should choose `rabbit` app and build its uber jar. And only its result to use for registration

**Comment by sgulzar-pivotal** [comment]
I am not aware of -PgenerareApps, how to set this profile, do you have any documentation on it including the later part?

**Comment by artembilan** [comment]
It is maven profile which is a part of app-starter plugin. You should use it manually when build the project: `mvnw install -PgenerateApps`

The docs on the matter on their way.
