### ISSUE TITLE
Test SSL configurations on PCC

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/gemfire#20]
The latest PCC 1.5 release supports the [TLS](https://docs.pivotal.io/p-cloud-cache/1-5/tls-enabled-app.html) option, so we would want to make sure the (Spring Boot) procedure explained in the docs specifically also works for our Apps.

**Comment by sabbyanandan** [comment]
If there's a problem, we would have to backport it to Darwin.

**Comment by tzolov** [comment]
Depends on PCF/PCC 1.5 + TLS environment

**Comment by sabbyanandan** [comment]
Tested and verified Darwin apps on the v1.5 release of PCC on PAS 2.3. Closing this as complete.
